Fix compilation on Visual Studio 2019 v16.11.42
Although Visual Studio 2022 allows function members in a templated class to use `requires`
(and this appears to be permitted by the language, although I haven't dug deeper than CPPReference here),
Visual Studio 2019 emits Error C7599, "a trailing requires clause is only allowed on a templated function"
when attempting to compile members of `linear_memory_resource`.

My solution is to make these functions templated as well, with a
default template argument equal to the class' template argument.
Since templated constructors can't be defaulted, I've added the
default implementation there as well.

Signed-off-by: Nia Bickford <nbickford@nvidia.com>